article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('addarticle/', views.addarticle, name='addarticle'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
#from user import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('articles/', views.articles, name='articles'),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('users/', include('user.urls')),
    path('todos/', include('todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_app.index, name='todo_index'),
    path('addtodo', views.todo_app.addtodo, name='todo_addtodo'),
    path('deletetodo/<int:id>', views.todo_app.deletetodo, name='todo_deletetodo'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

templates/includes/footer.html
{% load static %}
<footer class="py-2 bg-light col-cobalt-t">
  <div class="container-fluid">
    <div class="row text-center">
      <div class="col-md-6 mx-auto">
        <p class="lead my-auto">

            Copyright &copy; Ulaş Doğan Deniz 2019

            <img src="{% static 'article\img\facebook-icon.svg' %}"  height="35px" width="35px" alt="">


            <img src="{% static 'article\img\github-icon.svg' %}"    height="35px" width="35px" alt="">


            <img src="{% static 'article\img\twitter-icon.svg' %}"   height="35px" width="35px" alt="">

          /alkahesto
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light nav-cobalt fixed-top">
  <!-- Image and text -->
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'article\img\lotus-flower-white.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      LOTUS
    </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'articles' %}"><i class="fas fa-newspaper"></i> Makaleler</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#about"><i class="fas fa-info-circle"></i> Hakkımda</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'contact' %}"><i class="fas fa-phone"></i> İletişim</a>
      </li>
    </ul>

    <ul class="navbar-nav mx-auto">
      <li><a href="{% url 'todo:todo_index' %}" class="btn btn-outline-warning">Yapılacaklar</a></li>      
    </ul>

    <ul class="navbar-nav ml-auto">

      {% if request.user.is_authenticated %}
        <li class="nav-item active dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">Çıkış Yap</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Hesap Ayarları</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item active dropleft">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Giriş Yap/Kayıt Ol
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'user:login' %}">Giriş Yap</a>
            <a class="dropdown-item" href="{% url 'user:register' %}">Kayıt Ol</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item disabled" href="#">Yakında</a>
          </div>
        </li>
      {% endif %}

    </ul>



  </div>
</nav>

templates/includes/sidewidget.html
<!-- Sidebar Widgets Column -->
<div class="col-md-4 ">

  <!-- Search Widget -->
  <div class="card my-4">
      <form>
        <div class="input-group">
          {% csrf_token %}
          <input type="text" name="keyword" class="form-control" maxlength="64" placeholder="e.g. Django staticfiles">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-success my-2 my-sm-0">Ara</button>
          </span>
        </div>
      </form>
  </div>

  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Etiketler (Yakında)</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a class="btn btn-success btn-sm mb-1" href="#">#Web Design</a>
            </li>
            <li>
              <a class="btn btn-success btn-sm mb-1" href="#">#HTML</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a class="btn btn-success btn-sm mb-1" href="#">#JavaScript</a>
            </li>
            <li>
              <a class="btn btn-success btn-sm mb-1" href="#">#CSS</a>
            </li>
            <li>
              <a class="btn btn-success btn-sm mb-1" href="#">#Tutorials</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Side Widget -->
  <div class="card my-4">
    <h5 class="card-header text-center">Yazarlar</h5>
    <div class="card-body">
      <ul class="list-group">
        {% for user in users %}
        <li class="list-group-item">{{user.username}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>

</div>