blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
#from user import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('articles/', views.articles, name='articles'),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('users/', include('user.urls')),
    path('todos/', include('todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_app.index, name='todo_index'),
    path('addtodo', views.todo_app.addtodo, name='todo_addtodo'),
    path('deletetodo/<int:id>', views.todo_app.deletetodo, name='todo_deletetodo'),
]

todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    todo_title = models.CharField(max_length=25, verbose_name="Başlık")
    checked = models.BooleanField(verbose_name="Durum")

    def __str__(self):
        return self.todo_title

todo/views.py
from django.shortcuts import render, HttpResponse, redirect

from .models import Todo
# Create your views here.

class todo_app:

    def index(request):
        todos = Todo.objects.all()

        return render(request,"todo/todos.html", {"todos":todos})

    def addtodo(request):
        todo = Todo()
        todo.checked = False
        todo.todo_title = request.POST.get("todotitile")
        todo.save()


        return redirect("/todos/")

    def deletetodo(request, id):
        todo = Todo.objects.get(id=id)
        todo.delete()

        return redirect("/todos/")

templates/todo/todos.html
{% extends "../layout.html" %}
{% block content-w-nf %}
  <header class="neonSection">

    <div class="container">
      <div class="row text-center">
        <div class="col p-5">
          <a href="/" class="btn btn btn-danger float-left">Geri Dön</a>
          {% if request.user.is_authenticated %}
          <button type="button" class="btn btn-info float-right" data-toggle="modal" data-target="#exampleModalCenter">
            Ekle
          </button>
          {% endif %}

          <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Hedef Ekle</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form action="/todos/addtodo" method="post">
                  {% csrf_token %}
                  <div class="modal-body">
                    <input class="form-control" type="text" name="todotitile">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                  </div>
                </form>
              </div>
            </div>
          </div>

          <p class="display-1 neon3 text-font">Yapılacaklar</p>

          <div class="p-4 neon rounded text-light">

            {% for todo in todos %}
                <div class="mb-3 neon2 rounded" style="height: 32.97px">
                  <p class="my-auto mx-auto neon5">
                      <span>{{todo.todo_title}}</span>
                      <span><a href="{% url 'todo:todo_deletetodo' todo.id %}" class="btn btn-danger float-right btn-sm">Sil</a></span>
                  </p>
                </div>
            {% endfor %}

          </div>

        </div>
      </div>
    </div>
  </header>
{% endblock %}