article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('addarticle/', views.addarticle, name='addarticle'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
#from user import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('articles/', views.articles, name='articles'),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('users/', include('user.urls')),
    path('todos/', include('todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models

from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE, verbose_name="Kullanıcı")
    # on_delete= models.CASCADE -> user silindiği zaman user ile ilgili makale vb silinsin
    title = models.CharField(max_length=50, verbose_name="Başlık")
    category = models.ForeignKey('Category', verbose_name='Kategori', on_delete=models.CASCADE, null=True, blank=True)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    article_image = models.ImageField(blank=True, null=True, verbose_name="Makaleye Fotoğraf Ekleyin")
    views = models.PositiveIntegerField(default=0)
 


    def __str__(self):
        return self.title

    #class Meta:
    #    ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="İsim")
    comment_content = models.CharField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True, verbose_name="Yorum Tarihi")

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class Category(models.Model):
    category_name = models.CharField(max_length=25, verbose_name="Kategori İsmi")

    def __str__(self):
        return self.category_name

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category', 'content', 'article_image']

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Article,Comment
from .forms import ArticleForm
# Create your views here.

def index(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')

#------------------------------------------------------------------------------#
@login_required(login_url="/users/login/")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        # 1. Yol uzun
        """
        author = request.user
        title = form.cleaned_data.get("title")
        content = form.cleaned_data.get("content")

        newArticle = Article(author=author, title=title, content=content)
        newArticle.save()"""
        # 2. Yol
        article = form.save(commit=False) # commit = False -> newArticle.save()
        # form.save() formda verilenleri yerleştiriyor
        # article = Article(title=title, content=content)
        # biz formda kullanıcıyı göstermediğimiz için kullanıcıyı vermiyor
        # biz onu ayrı olarak kendimiz tanımlıyoruz
        article.author = request.user
        article.save()

        messages.success(request,"Makale Oluşturuldu")
        return redirect('/articles/dashboard/')
    return render(request, 'article/addarticle.html',{"form":form})

@login_required(login_url="/users/login/")
def delete(request, id):
    article = Article.objects.filter(id=id)
    article.delete()
    return redirect("/articles/dashboard/")

@login_required(login_url="/users/login/")
def update(request, id):
    article = get_object_or_404(Article, id=id)

    if article.author != request.user:
        return redirect('/articles/dashboard/')

    form = ArticleForm(request.POST or None,request.FILES or None, instance=article)
    if form.is_valid():

        form.save()
        messages.success(request,"Makale Düzenlendi")
        return redirect('/articles/dashboard/')
    return render(request, 'article/update.html', {'form': form})

def detail(request, id):
    keyword = request.GET.get("keyword")
    if keyword:
        article_byTitle = Article.objects.filter(title__icontains = keyword)
        article_byContent = Article.objects.filter(content__icontains = keyword)
        article_list = article_byTitle.union(article_byContent)
        return render(request,'articles.html',{'contacts': article_list})

    article = Article.objects.get(id = id)
    article.views+=1
    article.save()
    comment = article.comments.all()
    context = {
        "article":article,
        "comment":comment
    }
    return render(request,'article/detail.html', context)

@login_required(login_url="/users/login/")
def dashboard(request):
    article = Article.objects.filter(author=request.user)
    context = {
        "article":article
    }
    return render(request,'article/dashboard.html',context)

def articles(request):
    article_list = Article.objects.all()

    keyword = request.GET.get("keyword")
    if keyword:
        article_byTitle = Article.objects.filter(title__icontains = keyword)
        article_byContent = Article.objects.filter(content__icontains = keyword)
        article_list = article_byTitle.union(article_byContent)
        return render(request,'articles.html',{'articles': article_list})

    paginator = Paginator(article_list, 4) # Show 2 contacts per page
    page = request.GET.get('page')
    article_list = paginator.get_page(page)
    context = {
        #"article":Article.objects.all(),
        "users": User.objects.all(),
        'articles': article_list
    }
    return render(request,'articles.html',context)

def addcomment(request,id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author, comment_content=comment_content)

        newComment.article = article

        newComment.save()
    #return redirect("/articles/detail/" + str(id))
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/article/addarticle.html
{% extends "../layout.html" %}

{% load crispy_forms_tags %}

{% block title %}Makale Oluştur{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3 p-1">

    {% if messages %}
    <div class="text-center" role="alert">

      {% for message in messages %}
      <p {% if message.tags %} class="alert alert-{{ message.tags }} h2"{% endif %}>{{ message }}</p>
      {% endfor %}

    </div>
    {% endif %}

    <h1 class="display-3">Makale Oluştur</h1>

    <form method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{form.media}}
      {{form|crispy}}

      <br />

      <button type="submit" class="btn btn-success">Oluştur</button>

    </form>
  </div>
</div>
{% endblock %}

templates/article/dashboard.html
{% extends "layout.html" %}

{% block title %}Kontrol Paneli{% endblock %}

{% block content %}

  {% if messages %}
    <div class="text-center mt-2" role="alert">
      {% for message in messages %}
      <p {% if message.tags %} class="alert alert-{{ message.tags }} h2"{% endif %}>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <p class="display-3">Hoşgeldiniz {{request.user.username}}</p>

  <hr class="cobalt">

  <a href="/articles/addarticle" class="btn btn-success">Makale Oluştur</a>

  <hr class="cobalt">

  <div class="row">
    {% if article %}
      {% for article in article  %}
        <div class="col-4 mb-3">
          <div class="card" style="width: 22.7rem;">
            
            <div class="card-body">
              <h5 class="card-title">{{article.title}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{article.author}}</h6>
              <p class="card-text">{{ article.content|truncatewords:5|safe }}</p>
            </div>

            <div class="card-footer">
              <a href="/articles/delete/{{article.id}}" class="btn btn-danger btn-sm float-right ml-1">
                Sil
              </a>
              <a href="/articles/update/{{article.id}}" class="btn btn-success btn-sm float-right">
                Düzenle
              </a>
            </div>

          </div>
        </div>
      {% endfor %}
    {% else %}
    <div class="col text-center">
      <div class="alert alert-danger" role="alert">
        Henüz bir makaleniz bulunmuyor
      </div>
    </div>
    {% endif %}
  </div>

{% endblock %}

templates/article/detail.html
{% extends "../layout.html" %}
{% block title %}Makale: {{article.title}}{% endblock %}
{% block content %}
<div class="row ">
  <!-- Post Content Column -->
  <div class="col-lg-10 mx-auto">
    <!-- Title -->
    <p class="mt-4 display-3 text-center">{{article.title}}</p>

    <!-- Date/Time -->
    <p class="lead">
      <i class="fas fa-calendar-alt"></i> {{article.created_date}} -
      <i class="fas fa-user"></i> <a href="#">{{article.author}}</a> -
      <i class="far fa-eye"></i> {{article.views}}
    </p>
    <hr>
    <!-- Preview Image -->
    {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
    <hr>
    {% endif %}
    <!-- Post Content -->
    <div class="bg-light rounded p-1">
      <p>
        {{article.content|safe}}
      </p>
    </div>

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
      <h5 class="card-header">Yorum Ekle</h5>
      <div class="card-body">
        <form method="post" action="{% url 'article:addcomment' article.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">İsim</label>
            {% if request.user.is_authenticated %}
            <input name="comment_author" type="text" class="form-control" id="exampleInputEmail1" disabled value="{{request.user.username}}">
            {% else %}
            <input name="comment_author" type="text" class="form-control" id="exampleInputEmail1" placeholder="İsminizi Giriniz">
            {% endif %}
          </div>
          <div class="form-group">
            <label for="comment">Yorum</label>
            <textarea name="comment_content" class="form-control" rows="3" id="comment" placeholder="Yorum Yap"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>

    <hr>
      <p class="display-4 text-center">Yorumlar</p>

    <!-- Single Comment -->
    {% if comment %}
    {% for comment in comment %}
      <div class="media mb-4">
        <div class="media-body bg-light p-2">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
          <small>{{comment.comment_date}}</small>
          <p>{{comment.comment_content}}</p>
        </div>
      </div>
    {% endfor %}
    {% endif %}

    <!-- EĞER KULLANICI GİRİŞ YAPMIŞSA İSİM OTO DOLDURULSUN -->

    <!-- Comment with nested comments
    <div class="media mb-4">

      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">

        <h5 class="mt-0">Commenter Name</h5>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibu
        <div class="media mt-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <div class="media mt-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

      </div>

    </div>-->



  </div>



</div>
{% endblock %}

templates/article/update.html
{% extends "../layout.html" %}

{% load crispy_forms_tags %}

{% block title %}Düzenle{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">

    {% if messages %}
    <div class="text-center mt-2" role="alert">

      {% for message in messages %}
      <p {% if message.tags %} class="alert alert-{{ message.tags }} h2"{% endif %}>{{ message }}</p>
      {% endfor %}

    </div>
    {% endif %}

    <h1 class="display-3">Düzenle</h1>

    <form method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{form.media}}
      {{form|crispy}}

      <br />

      <button type="submit" class="btn btn-success">Güncelle</button>

    </form>
  </div>
</div>
{% endblock %}